---
- hosts: all
  become: yes
  tasks:
    - name: Update packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install OpenJDK
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true
